image: registry.gitlab.com/vician/mkdocs:latest

before_script:
    - mkdir -p $HOME/.ssh
    - chmod 700 $HOME/.ssh
    - rm -f $HOME/.ssh/known_hosts
    - echo "$SSH_HOST ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDDoLhgavd5zWF8C+/BKlM15LNtpaaUkL03b44KYKxJ0DVf54zd6PO4pZxmZYorkNtsVHkOsJbXm2rmVrvdGBMU=" >> $HOME/.ssh/known_hosts
    - ssh-keyscan -t rsa,dsa,ecdsa github.com >> $HOME/.ssh/known_hosts
    - chmod 644 $HOME/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add -D
    - echo -en "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-add -l

test:
    script:
        - mkdocs build
    except:
        - master

deploy:
    script:
        - sed -i "s/&copy;/\&copy; $(date +%Y)/g" mkdocs.yml
        - sed -i "s/REF/#$(git log --pretty=format:'%h' -n 1)/g" mkdocs.yml
        - sed -i "s/HASH/$(git rev-parse HEAD)/g" mkdocs.yml
        - mkdocs build
        - rsync -e "ssh" -avz --delete --exclude="\.*" site/* $SSH_USER@$SSH_HOST:$SSH_ROOT/
    artifacts:
        paths:
            - site
    only:
        - master

mirror-master:
    script:
        - git remote add upstream git@github.com:vician/wiki || true
        - git fetch upstream
        - git push --force --progress upstream HEAD:master
    only:
        - master

mirror-tags:
    script:
        - git remote add upstream git@github.com:vician/wiki || true
        - git fetch upstream
        - git push --force --progress --tags upstream HEAD:master
    only:
        - tags
