site_name: Martin Vician's wiki

theme:
    name: material
    palette:
        primary: teal
        accent: teal

extra_javascript:
- "jquery-3.2.1.min.js"
- "whichdistro.js"
- "Chart.bundle.js"
- "bootstrap.min.js"
- "bootstrap-slider.min.js"
extra_css:
    #- "bootstrap.min.css"
- "bootstrap-slider.css"

extra:
    logo: 'favicon.ico'
    social:
        - type: 'twitter'
          link: 'https://twitter.com/ptvician'
    search:
        language: 'en, cs'


repo_url: 'https://gitlab.com/vician/wiki'
