site_name: Martin Vician's wiki

theme:
    name: material
    palette:
        primary: teal
        accent: teal

extra:
    logo: 'favicon.ico'
    social:
        - type: 'twitter'
          link: 'https://twitter.com/ptvician'
    search:
        language: 'en, cs'


repo_url: 'https://gitlab.com/vician/wiki'
