site_name: Martin Vician's wiki
site_author: Martin Vician

theme:
    name: material
    palette:
        primary: teal
        accent: teal
    favicon: 'icon.png'
    logo: 'icon.png'

markdown_extensions:
- footnotes

extra_javascript:
- "jquery-3.2.1.min.js"
- "whichdistro.js"
- "Chart.bundle.js"
- "bootstrap.min.js"
- "bootstrap-slider.min.js"
extra_css:
    #- "bootstrap.min.css"
- "bootstrap-slider.css"

extra:
    social:
        - type: 'globe'
          link: 'https://www.vician.cz'
        - type: 'twitter'
          link: 'https://twitter.com/ptvician'
        - type: 'gitlab'
          link: 'https://gitlab.com/vician'
        - type: 'github'
          link: 'https://github.com/vician'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/ptvician/'
        - type: 'lock' #keybase not included in current font-awesome
          link: 'https://keybase.io/vician'
    search:
        language: 'en'

repo_name: 'vician/wiki'
repo_url: 'https://gitlab.com/vician/wiki'
edit_uri: ''

google_analytics:
    - 'UA-73656343-10'
    - 'auto'


copyright: "&copy; Martin Vicián <a href='https://gitlab.com/vician/wiki/commit/HASH'>REF</a>"
